---
- name: Bootstrap K3s Kubernetes Control Plane
  hosts: coordinator
  become: true
  vars:
    private_vlan_interface: "eth0.100"
  tasks:
    - name: Download and install K3s Server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
          --cluster-init \
          --node-ip={{ ansible_facts[private_vlan_interface]['ipv4']['address'] }} \
          --flannel-iface={{private_vlan_interface}} \
          --disable servicelb \
          --disable traefik
      args:
        creates: /usr/local/bin/k3s

    - name: Extract the Cluster Join Token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_b64

    - name: Set cluster token fact for worker registration
      ansible.builtin.set_fact:
        k3s_cluster_token: "{{ k3s_token_b64.content | base64decode | trim }}"
        delegate_to: localhost
        delegate_facts: true

- name: Join Worker ComputeBlades to Kubernetes Cluster
  hosts: workers
  become: true
  vars:
    # Pulls the token dynamically from the coordinator task
    cluster_token: "{{ hostvars['localhost']['k3s_cluster_token'] }}"
    coordinator_host: "{{ groups['coordinator'][0] }}"
    private_vlan_interface: "eth0.100"
  tasks:
    - name: Get coordinator private VLAN IP address
      ansible.builtin.set_fact:
        coordinator_private_ip: "{{ hostvars[coordinator_host]['ansible_facts'][private_vlan_interface]['ipv4']['address'] }}"

    - name: Download and install K3s Agent on workers
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ coordinator_private_ip }}:6443" K3S_TOKEN="{{ cluster_token }}" sh -s - agent \
          --node-ip={{ ansible_facts[private_vlan_interface]['ipv4']['address'] }} \
          --flannel-iface={{private_vlan_interface}}
      args:
        creates: /usr/local/bin/k3s-agent
